name: Integration

on:
  branch_protection_rule:
    types: [created, edited, deleted]
  push:
    branches: [main]
  pull_request:
    branches: [main]

  jobs:
    unit-tests:
      runs-on: ubuntu-latest

      strategy:
        matrix:
          node-version: [18.x, 16.x]

      steps:
        - uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
        - name: npm install
          run: npm ci
        - name: tests
          run: npm test
    build:
      runs-on: ubuntu-latest

      strategy:
        matrix:
          node-version: ['18.x, 16.x']

      steps:
        - uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v2
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'npm'
        - run: npm i
        - run: npm run build
    Lint: 
      runs-on: ubuntu-latest
      steps:
        - name: Check out Git repository
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - uses: actions/setup
          with:
            eslint: true
            node-version: ${{ matrix.node-version }}
            cache: 'npm'
        - run: npm i
        - run: npm lint